/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javajni_JavaJNI */

#ifndef _Included_javajni_JavaJNI
#define _Included_javajni_JavaJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javajni_JavaJNI
 * Method:    nativePrint
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javajni_JavaJNI_nativePrint
  (JNIEnv *, jobject, jint);

/*
 * Class:     javajni_JavaJNI
 * Method:    nativeChange
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_javajni_JavaJNI_nativeChange
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
